### ISSUE TITLE
Fix up broken/empty categories & filters

### ISSUE THREAD

**Issue by Codeshark-NET** [protontypes/open-climate-impact#13]

**Comment by andrew** [comment]
I think this will get fixed by https://github.com/ecosyste-ms/ost/issues/80

**Comment by Codeshark-NET** [comment]
> I think this will get fixed by [ecosyste-ms/ost#80](https://github.com/ecosyste-ms/ost/issues/80)

Partly yes - but there were some other issues with the filters - fixed it now. :-)
