### ISSUE TITLE
Better date field for "last activity"

### ISSUE THREAD

**Issue by andrew** [protontypes/open-climate-impact#6]
The code at https://github.com/protontypes/open-climate-impact/blob/main/data/index.ts#L35C52-L35C52 uses `last_synced_at` from OST, but that doesn't mean the repo was updated, it's just when OST last checked for updates, regardless of if there were any.

Two better fields on the `repository` object of the project are `pushed_at` (when a commit was last pushed to the main branch or `updated_at` when anything has changed, issues, pull reqests, commits, branches etc

**Comment by Codeshark-NET** [comment]
Fixed with https://github.com/protontypes/open-climate-impact/commit/f71ebdf9f3aa9500d327e9d117c487c8014f43cf , thanks! 🙌
